apiVersion: v1
kind: Pod
metadata:
  name: app-volume
spec:
  containers:
    - image: lytvynovkostiantyn/my-demo:v1.0.0
      name: app
 
      livenessProbe:
        httpGet:
          path: /
          port: 8080
        initialDelaySeconds: 5
        timeoutSeconds: 1
        periodSeconds: 10
        failureThreshold: 3
 
      readinessProbe:
        httpGet:
          path: /
          port: 8080
        periodSeconds: 2
        initialDelaySeconds: 0
        failureThreshold: 3
        successThreshold: 1
      
      ports:
        - containerPort: 8080

      volumeMounts:
      - name: "data"
        mountPath: "/data"


  volumes:
    - name: "data"
      hostPath:
        path: "/var/lib/app"
